# 公開するページのURL
baseURL = "https://htako.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "htako memo"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "htako"
    bio = "まとまってないけど書いておきたいやつのあつまりです。"
    avatar = ""

[Params]
    DateForm = "2.1.2006"
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "htako_tech"
  github = "htako"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

